### ISSUE TITLE
【2023年3月7日】部署服务过程中出现文件路径错误

### ISSUE THREAD

**Issue by hsmbs** [soulteary/flare#15]
控制台输出的报错结果如下：
`internal/editor/editor.go:22:12: pattern editor-assets: no matching files found`
`internal/guide/guide.go:21:12: pattern guide-assets: no matching files found`

引起报错的代码是embed包给出的路径错误；
internal目录下editor.go和guide.go无法找到editor-assets和guide-assets资源文件

没学go语言，所以找不到根源在哪，不断试错才找到一个解决办法，全程表述如果有误请见谅，方法如下：
将`flare/embed/vendor/editor-assets`移动到`/flare/internal/editor/editor-assets`
将`flare/embed/vendor/guide-assets`移动到`/flare/internal/guide/guide-assets`
再运行go run main.go即可正常运行服务

详细部署过程及解决方式参考：https://zhuanlan.zhihu.com/p/611890668?

**Comment by LightAPIs** [comment]
项目里不是有个 `build/build.go` 文件吗 🤣

**Comment by hsmbs** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hsmbs** [comment]
> 项目里不是有个 `build/build.go` 文件吗 🤣

不太懂这个啊，但是我也尝试运行了，同样的报错

**Comment by soulteary** [comment]
先执行 `go run build/build.go`，让静态资源就绪。
