### ISSUE TITLE
修改配置之后配置会生效，但是网页上还是显示原来的配置

### ISSUE THREAD

**Issue by zbw94** [soulteary/flare#4]
修改下图这个配置之后，配置会生效，应用能保持原来的大小写，但是网页显示的配置还是`否`
修改配置之后：
<img width="228" alt="image" src="https://user-images.githubusercontent.com/16416594/191409351-fb337ead-0290-4156-a919-d48737c4ae71.png">

config.yml:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/16416594/191409176-e8f63341-39f0-4ae5-80ec-eae198fd4c41.png">

**Comment by LightAPIs** [comment]
发现这个 issue 就是之前提的这个 pr(#17)
